### ISSUE TITLE
Unable to install with Kibana 6.2.4

### ISSUE THREAD

**Issue by Blason** [socprime/soc_workflow_app_ce#1]
Hi,

I am unable to install said app in kibana 6.2.4 with below error. Can you please help?

:/usr/share/kibana/bin# ./kibana-plugin install file:///var/soc_workflow_app_ce-master.zip
Attempting to transfer from file:///var/soc_workflow_app_ce-master.zip
Transferring 6154753 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

**Comment by thisisunreal** [comment]
> 
> 
> Hi,
> 
> I am unable to install said app in kibana 6.2.4 with below error. Can you please help?
> 
> :/usr/share/kibana/bin# ./kibana-plugin install file:///var/soc_workflow_app_ce-master.zip
> Attempting to transfer from file:///var/soc_workflow_app_ce-master.zip
> Transferring 6154753 bytes....................
> Transfer complete
> Retrieving metadata from plugin archive
> Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

You're trying the wrong .zip. Extract that and it's in /dist/soc_workflow_app_XXXX.zip

**Comment by socprime** [comment]
Thank you for your reply!
Archive for installing app is located in the /dist/soc_workflow_app_XXXX.zip path
