### ISSUE TITLE
Playbooks Menu Disappears 

### ISSUE THREAD

**Issue by megadevx** [socprime/soc_workflow_app_ce#3]
## Expected Behavior
The playbooks menu will display.

## Current Behavior
The playbooks menu will show then rise up the screen and then disappear. 
![soc_workflow_issue_playbook_menu](https://user-images.githubusercontent.com/26330783/50294936-996b3680-043c-11e9-81be-801074640868.gif)
After this initial click, the menu will not display with this error again until the page is reloaded in some manner.

## Steps to Reproduce
1. Start Kibana with the Soc Workflow App installed
2. Navigate to the App Page
3. Click on the Playbooks Menu

## Context (Environment)
**OS**: Ubuntu 16.04.4 LTS
**Kibana**: 5.6.0
**Soc Workflow App**: 1.6.3
Followed the steps to install, but I had to do the repackaging described in issue #2. Another difference in installation was that I didn't use elasticdump to upload the sigma documents, but I used a python script that I wrote to index those documents.

**Comment by XizzoR** [comment]
Exactly the same issue. Fresh plugin install (didn't have to do repackaging of "deepmerge"), first attempt to open app in Kibana (6.5.1) and I have made no upload yet.

**Comment by socprime** [comment]
Thank you for your report!
Currently tested version of Kibana for this app is 6.3.0. This problem may occur in different versions. In newest version of Kibana there are some bugs which we already working with, but update to github repo will be in the beginning of 2019.
