### ISSUE TITLE
Unknown message in app header

### ISSUE THREAD

**Issue by XizzoR** [socprime/soc_workflow_app_ce#4]
Hello there!

I think there are some frontend bug(s) which affects the position of [this](https://imgur.com/a/4NUgAnX) message (talking about Yes/No message-box with bright blue background colour). I guess it's nothing important, but just to let you know. 

soc_workflow_app version = 1.6.3
Kibana version = 6.5.1
Browsers = Chrome, Mozilla, Safari

Cheers!

**Comment by XizzoR** [comment]
Update: I forgot about that "permission to send stats" message that pops up on first Kibana UI usage. That is the message-box I am talking about.

**Comment by socprime** [comment]
Thank you for your report!
It is known problem, it’s native Kibana window with request about "permission to send status", it is only displayed when you are using fresh Kibana install and after you make your decision it is never shown again. In new releases this issue will be fixed.

**Comment by XizzoR** [comment]
Understood, thanks! 
Happy Holidays!
