### ISSUE TITLE
Unable to "Create Case"

### ISSUE THREAD

**Issue by thisisunreal** [socprime/soc_workflow_app_ce#6]
I'm receiving the following error when I click _Save_ after trying to use the _Create Case_ feature.

Version: 6.6.1
Build: 19513
Error: TypeError: scope.saveCase is not a function (https://xxx.xxx.xxx.xxx/bundles/soc_workflow_ce.bundle.js:115)
window.onerror@https://xxx.xxx.xxx.xxx/bundles/commons.bundle.js:3:935888

**Comment by socprime** [comment]
Hello, @thisisunreal!
Thank you for your report.

I can not reproduce this bug.
Try to reinstall application and check:
- that your Elasticsearch and Kibana have similar versions;
- you posted all four index templates
